version: '2'
services:
  php:
    image: yiisoftware/yii2-php:7.1-apache
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    networks:
      - skynet
    ports:
      - '8000:80'
networks:
  skynet:
    external:
      name: skynet